import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from app.domain.templates.models import TEMPLATES, DocumentTemplate, TemplateType, TemplateField


class TemplateRenderer:
    def render_markdown(self, template_type: TemplateType, data: dict[str, str]) -> str:
        template = TEMPLATES[template_type]
        missing = template.validate_fields(data)
        if missing:
            return self._error_missing_fields(missing, template)
        body = template.body_markdown
        for key, value in data.items():
            placeholder = "{" + key + "}"
            body = body.replace(placeholder, value.strip() if value else "")
        body = self._clean_unused_placeholders(body)
        header = self._build_header(template, data)
        return header + "\n\n---\n\n" + body

    def render_docx(
        self,
        template_type: TemplateType,
        data: dict[str, str],
        output_path: Path,
    ) -> Path:
        try:
            from docx import Document
            from docx.shared import Pt, Inches, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
        except ImportError:
            msg = "python-docx is required for DOCX export. Install with: poetry add python-docx"
            raise RuntimeError(msg)

        template = TEMPLATES[template_type]
        missing = template.validate_fields(data)
        if missing:
            msg = f"Missing required fields: {', '.join(missing)}"
            raise ValueError(msg)

        doc = Document()

        title = doc.add_heading(template.title, level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        meta = doc.add_paragraph()
        meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = meta.add_run(f"Generated by Nyaya Mitra on {datetime.now().strftime('%d-%m-%Y')}")
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

        body_text = self.render_markdown(template_type, data)
        lines = body_text.split("\n")

        for line in lines:
            if not line.strip():
                doc.add_paragraph()
            elif line.startswith("### "):
                doc.add_heading(line[4:], level=3)
            elif line.startswith("## "):
                doc.add_heading(line[3:], level=2)
            elif line.startswith("# "):
                doc.add_heading(line[2:], level=1)
            elif line.startswith("| "):
                pass
            elif line.startswith("---"):
                pass
            elif line.startswith("**") and line.endswith("**"):
                p = doc.add_paragraph()
                run = p.add_run(line.strip("*"))
                run.bold = True
            else:
                p = doc.add_paragraph(line)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(str(output_path))
        return output_path.resolve()

    def render_text(self, template_type: TemplateType, data: dict[str, str]) -> str:
        md = self.render_markdown(template_type, data)
        clean = re.sub(r"[#*|\[\]]", "", md)
        clean = re.sub(r"\n{3,}", "\n\n", clean)
        return clean.strip()

    def get_fields_summary(self, template_type: TemplateType) -> list[dict]:
        template = TEMPLATES[template_type]
        return [
            {
                "key": f.key,
                "label": f.label,
                "description": f.description,
                "required": f.required,
                "placeholder": f.placeholder,
            }
            for f in template.fields
        ]

    def get_template_info(self, template_type: TemplateType) -> dict:
        template = TEMPLATES[template_type]
        return {
            "type": template.template_type.value,
            "title": template.title,
            "description": template.template_type.description(),
            "applicable_acts": template.template_type.applicable_acts(),
            "instructions": template.instructions,
            "fee_info": template.fee_info,
            "fields": self.get_fields_summary(template_type),
        }

    def _build_header(self, template: DocumentTemplate, data: dict) -> str:
        lines = [f"# {template.title}", ""]
        lines.append(f"**Generated by Nyaya Mitra** | {datetime.now().strftime('%d-%m-%Y %H:%M')}")
        lines.append("")
        lines.append(f"**Applicable Law:** {'; '.join(template.template_type.applicable_acts())}")
        if template.fee_info:
            lines.append("")
            lines.append(f"**Fee Info:** {template.fee_info}")
        return "\n".join(lines)

    def _error_missing_fields(self, missing: list[str], template: DocumentTemplate) -> str:
        lines = [
            "# Missing Required Fields",
            "",
            f"Please fill in the following required fields for **{template.title}**:",
            "",
        ]
        for field_name in missing:
            lines.append(f"- {field_name}")
        lines.append("")
        lines.append("These fields are necessary to generate the document.")
        return "\n".join(lines)

    def _clean_unused_placeholders(self, text: str) -> str:
        text = re.sub(r"\{[^}]+\}", "", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        text = re.sub(r"^\s*$(\n)", "", text, flags=re.MULTILINE)
        return text.strip()


renderer = TemplateRenderer()
